import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const inter = Inter({
  subsets: ["latin"], // Add required subsets
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Include all weights
  variable: "--font-inter", // Optional: Use as a CSS variable
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${inter.className} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
